INSERT INTO SHAPE (ID, POSX, POSY, COLOR, SHAPE_TYPE) VALUES (1, 20, 20, '#000000', 'square')
INSERT INTO SQUARE (ID, WIDTH) VALUES (1, 100)
INSERT INTO SHAPE (ID, POSX, POSY, COLOR, SHAPE_TYPE) VALUES (2, 0, 0, '#FF0000', 'rectangle')
INSERT INTO RECTANGLE (ID, WIDTH, LENGTH) VALUES (2, 10, 100)
