INSERT INTO SHAPE (DTYPE, POSX, POSY, WIDTH, COLOR, SHAPE_TYPE) VALUES ('Square', 20, 20, 30, '#000000', 'square')

INSERT INTO SHAPE (DTYPE, POSX, POSY, WIDTH, LENGTH, COLOR, SHAPE_TYPE) VALUES ('Rectangle', 0, 0, 10, 100, '#FF0000', 'rectangle')
